name: Pull docker image
description: Pull docker image

inputs:
  image:
    description: The docker image to pull
    required: true
    default: ssg-image:v1.0

  tag:
    description: The tag to apply to the pulled image
    required: false
    default: v1.0

runs:
  using: "composite"
  steps:
    - name: Login to Amazon ECR
      shell: bash
      run: |
        aws ecr get-login-password --region us-west-2 \
        | docker login --username AWS --password-stdin 418295714268.dkr.ecr.us-west-2.amazonaws.com
        echo "Login successful."

    - name: Pull Docker image
      shell: bash
      run: |
        echo "Pulling Docker image: ${{ inputs.image }}"
        docker pull 418295714268.dkr.ecr.us-west-2.amazonaws.com/ssg/${{ inputs.image }}
        echo "Docker image pulled successfully:"
        docker tag 418295714268.dkr.ecr.us-west-2.amazonaws.com/ssg/${{ inputs.image }} ssg-image:${{ inputs.tag }}
