name: pre_merge

on:
  pull_request_target:
    branches: [ main ]

jobs:
  load_parameters:
    uses: qualcomm/minkipc/.github/workflows/loading.yml@main
    secrets: inherit
    with:
      event_name: ${{ github.event_name }}
      pr_ref: ${{ github.event.pull_request.head.ref }}
      pr_repo: ${{ github.event.pull_request.head.repo.full_name }}

  build:
    needs: load_parameters
    uses: qualcomm/minkipc/.github/workflows/sync_build.yml@main
    secrets: inherit
    with:
      docker_image: ssg-image:v1.0
      build_matrix: ${{ needs.load_parameters.outputs.build_matrix }}
      event_name: ${{ github.event_name }}
      pr_ref: ${{ github.event.pull_request.head.ref }}
      pr_repo: ${{ github.event.pull_request.head.repo.full_name }}

  check_run:
    runs-on: ubuntu-latest
    needs: [init-status, loading, build]
    steps:
      - name: Post check run
        uses: qualcomm/minkipc/.github/actions/check_run@main
        with:
          sha: ${{ inputs.sha }}
          repo: ${{ inputs.repo }}
          s3_location: ${{ needs.build.outputs.s3_location }}
          APPID: ${{ secrets.APPID }}
          PVK: ${{ secrets.PVK }}
